apiVersion: batch/v1
kind: CronJob
metadata:
  name: plaid-recurring-job
spec:
  schedule: "0 0 15 * *"  # Runs on the 15th of every month at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: plaid-app
            image: plaid-app:latest  # Ensure you have pushed your Docker image to a registry
            env:
            - name: PLAID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: plaid-secrets
                  key: client_id
            - name: PLAID_SECRET
              valueFrom:
                secretKeyRef:
                  name: plaid-secrets
                  key: secret
            - name: PLAID_PUBLIC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plaid-secrets
                  key: public_token
          restartPolicy: OnFailure
